@startuml ConfigurationScenario
!pragma teoz true

title "Microservice Configuration Success Scenario"
hide footbox
box "Internal Services" #LightBlue
collections GatewayService
collections ConfigService
collections AuthService
end box

box "Microservices"
collections CustomerService
end box


==Init Started==
note over ConfigService: Service configurations \n application-dev.yml \n application-prod.yml \n application.yml \n client-service \n ... application.yml \n ... application-anotherprofile.yml\n another-client-service \n ... application.yml

ConfigService -> ConfigService : config=loadConfig()
GatewayService -> ConfigService ++ : getConfig()
return config 
 AuthService -> ConfigService ++ : getConfig()
return config  
 CustomerService -> ConfigService ++ : getConfig()
return config 
==Init Finish==

alt When config changed
ConfigService -> GatewayService : refreshConfig(config)
ConfigService -> AuthService : refreshConfig(config)
ConfigService -> CustomerService : refreshConfig(config)
end


@enduml