@startuml StartupScenario
!pragma teoz true

title "Service Registration Scenario"
hide footbox
box "Internal Service" #LightBlue
collections GatewayService
collections DiscoveryService
collections AuthService
end box

box "Microservices"
collections CustomerService
end box


==Init Started==
GatewayService -> DiscoveryService ++ : register(urlAddress, serviceName)
return return OK 
 AuthService -> DiscoveryService ++ : register(urlAddress, serviceName)
return return OK
 CustomerService -> DiscoveryService ++ : register(urlAddress, serviceName)
return return OK 
==Init Finish==

loop Periodically
GatewayService -> DiscoveryService : healthCheck(loadStatus)
AuthService -> DiscoveryService : healthCheck(loadStatus)
CustomerService -> DiscoveryService : healthCheck(loadStatus)
end


@enduml