@startuml CustomerRegistrationScenario
!pragma teoz true

title "Customer Registration Success Scenario"

hide footbox
actor Customer


box "Internal Services" #LightBlue
collections GatewayService
collections LoadBalancer
collections DiscoveryService
collections AuthService
queue MessageQueueBroker
end box

box "Microservices"
collections MS1
database MS1DB
database AuthDB
end box

Customer -> GatewayService ++ : ms1/\napi(ms1Inf, authInf)
GatewayService -> LoadBalancer ++ : ms1/\napi(ms1Inf, authInf)
LoadBalancer -> DiscoveryService ++ : getServiceInfo(MS1)
return serviceAddress 
LoadBalancer -> MS1 ++ : serviceAddress/ms1/api(ms1Inf, authInf)
MS1 -> MS1DB ++: insert(ms1Inf)
return return OK 
MS1 -> MessageQueueBroker ++ : pushMessage(authInf)
MessageQueueBroker -> AuthService ++ : dispatch(newms1Inf)
AuthService -> AuthDB ++ : insert(authInf)
return return OK 
AuthService -> MessageQueueBroker -- : updateMessage(OK)
MessageQueueBroker -> MS1 -- : dispatch(OK)
return return OK 
return return OK 

@enduml