@startuml MovieAppScenario
!pragma teoz true

title "Movie App Example Scenario"

hide footbox
actor Customer


box "Internal Services" #LightBlue
participant GatewayService
participant LoadBalancer
participant DiscoveryService
participant AuthService
end box

box "Microservices"
participant MovieAppMS
end box
loop Periodically
GatewayService -> GatewayService : block = createBlock()
GatewayService -> GatewayService : addTransactions(transactionList)
GatewayService -> GatewayService : appendChain(block)
end
Customer -> GatewayService ++ : movie/\ngetFilm(movieInf, authInf)
GatewayService -> LoadBalancer ++ : movie/\ngetFilm(movieInf, authInf)
LoadBalancer -> DiscoveryService ++ : getServiceInfo(movie)
return serviceAddress 
LoadBalancer -> MovieAppMS ++ : serviceAddress/movie/getFilm(movieInf, authInf)
LoadBalancer -> LoadBalancer: tx = addTransaction(CB,MovieAppMS,movieInf)
LoadBalancer ->? : << diffuse tx to all >>
MovieAppMS -> AuthService ++ : pushMessage(authInf)
AuthService -> MovieAppMS -- : dispatch(OK)
return return OK 
return return OK 

@enduml