@startuml PrimeAppScenario
!pragma teoz true

title "Prime App Example Scenario"

hide footbox
actor Customer


box "Internal Services" #LightBlue
participant GatewayService
participant LoadBalancer
participant DiscoveryService
participant AuthService
end box

box "Microservices"
participant PrimeAppMS
end box
loop Periodically
GatewayService -> GatewayService : block = createBlock()
GatewayService -> GatewayService : addTransactions(transactionList)
GatewayService -> GatewayService : appendChain(block)
end
Customer -> GatewayService ++ : prime/\ncalculate(upperPrimeLimit ,authInf)
GatewayService -> LoadBalancer ++ : prime/\ncalculate(upperPrimeLimit, authInf)
LoadBalancer -> DiscoveryService ++ : getServiceInfo(prime)
return serviceAddress 
LoadBalancer -> PrimeAppMS ++ : serviceAddress/prime/calculate(upperPrimeLimit, authInf)
LoadBalancer -> LoadBalancer: tx = addTransaction(CB,PrimeAppMS,upperPrimeLimit)
LoadBalancer ->? : << diffuse tx to all >>
PrimeAppMS -> AuthService ++ : checkAuthenticate(authInf)
AuthService -> PrimeAppMS -- : return(primeNumber)
return return primeNumber 
return return primeNumber 

@enduml