@startuml ServeAppScenario
!pragma teoz true

title "Serve App Example Scenario"

hide footbox
actor Customer


box "Internal Services" #LightBlue
participant GatewayService
participant LoadBalancer
participant DiscoveryService
participant AuthService
end box

box "Microservices"
participant ServeAppMS
end box

Customer -> GatewayService ++ : serve/\ngetMovieAndPrime(serveInf, authInf)
GatewayService -> LoadBalancer ++ : serve/\ngetMovieAndPrime(serveInf, authInf)
LoadBalancer -> DiscoveryService ++ : getServiceInfo(serve)
return serviceAddress 
LoadBalancer -> ServeAppMS ++ : serviceAddress/serve/getMovieAndPrime(serveInf, authInf)
LoadBalancer -> LoadBalancer: tx = addTransaction(CB,ServeAppMS,serveInf)
LoadBalancer ->? : << diffuse tx to all >>
ServeAppMS -> AuthService ++ : pushMessage(authInf)
AuthService -> ServeAppMS -- : dispatch(OK)
return return OK 
return return OK 

@enduml